### PR TITLE
Extra languages

### PR DESCRIPTION
**Pull request by grctest**
danish, spanish, estonian, french, italian, japanese, korean, portugese and thai

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
How is the quality of those translations? Machine translated?

**Comment by grctest** [comment]
Yeah they were translated using the following tool: https://translate.i18next.com

The tool uses google translate, but avoids translating the keys (which can happen if you try to translate i18n json via the ui).

The tool recommends using [locize](https://locize.com) if we want a better experience, but more languages would need a scrolling language dropdown menu and a more scalable method of importing the i18n json files.

**Comment by sschiessl-bcp** [comment]
Could we do a on-the-fly translation button? We only maintain "en" language, and user can select a language and it gets auto translated?

**Comment by grctest** [comment]
I don't think so without paying for a premium service.

We would also need to take into consideration the geo-blocking that some translation services users may run into.

**Comment by sschiessl-bcp** [comment]
Do we know anyone to proofread? Not sure if autotranslated makes UX easier, especially in such technical terms. What do you think?=

**Comment by grctest** [comment]
Requiring a peer review for each new language sounds good to me, asking the community is probably the best bet.

Just reading the locale files might not make sense, checking out the locale use in app might be required of the peer reviewers.

**Comment by grctest** [comment]
Updated the translations, taking telegram feedback into account the beet branding has been removed from the translation files to avoid beet being translated like a vegetable, lol.

The HTLC acronym has been extended to 'hash time locked contract' then translated in the non-english locales.

**Pull request merged**
