### PR TITLE
Merge develop branch into master branch

### PR DESCRIPTION
**Pull request by abitmore**
This pull request is to track all changes made in the `develop` branch. We will merge it as we see fit.

### CODE REVIEW

**Comment by grctest** [comment]
Once the following PR is merged, we should create another release candidate release with these changes 👍 https://github.com/bitshares/beet/pull/260

**Comment by sschiessl-bcp** [comment]
> Once the following PR is merged, we should create another release candidate release with these changes 👍 #260

This is already included now

**Comment by grctest** [comment]
Added another PR to merge into the develop branch: https://github.com/bitshares/beet/pull/276

**Comment by grctest** [comment]
Can we merge this into the primary repo branch now the release candidate v2 is out?

We could then create another develop branch to continue developments

Thanks

**Comment by grctest** [comment]
@abitmore @sschiessl-bcp Let's merge the develop branch into the master branch. We can then re-create this PR to keep track of any further changes.

**Review by sschiessl-bcp — APPROVED** [review]

**Pull request merged**
