### PR TITLE
Reintroduce cryptos & add Hive

### PR DESCRIPTION
**Pull request by grctest**
Added BNB, BNB_TEST, STEEM, EOS, TLOS back, and introduced HIVE.

WLS is still in maintenance until they've resolved library package dependency updates.

Not yet tested, could be misconfigured or not full featured yet.

### CODE REVIEW

**Comment by grctest** [comment]
Time since last release:
https://github.com/EOSIO/eosjs 1 year ago
https://github.com/bnb-chain/javascript-sdk 1 year ago
https://gitlab.com/beyondbitcoin/wlsjs 2 years ago
https://www.npmjs.com/package/steem 3 years ago

Some of these libraries are reporting dependency vulnerabilities, to resolve some of these warnings we could include `npm audit fix -force` to apply the change, others we would need to fork the repo to update the dependency hopefully without introducing breaking changes.

**Comment by sschiessl-bcp** [comment]
Hive should be a good start imho, and obviously Bitcoin.

Steem, WhaleShares might still work with Hivejs. Binance chain was a mess back then, crazy doendencies. EOS has plenty of competitors. Any lib with crazy dependencies I would nkt reintroduce yet atp

**Comment by grctest** [comment]
I've disabled BNB once again, once maintained again we could re-evaluate it.

You mean we should make a hivebasedchain class instead of steembasedchain? Since hive-js is more maintained? Assuming it's still backwards compatible despite their several hard forks upgrades?

**Comment by abitmore** [comment]
Anyway, I think this is low priority at the moment. Please focus on the main features first. Thanks.

**Comment by grctest** [comment]
Perhaps TUSC should also be put on maintenance till their key issues are resolved?

**Comment by sschiessl-bcp** [comment]
lets rediscuss later and reopen when priority

**Pull request closed without merging**
