### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by abitmore**
Tracker for development by @grctest.

(The following is copied from https://github.com/bitshares/beet/pull/181#issuecomment-1205882774)

Summary of changes in PR:
* npm-check-updates was initially used to identify packages which could be updated
  * About half of the packages were able to be updated with minor changes
  * Some of the updated packages introduced severe breaking changes, namely vue2 -> vue3
    * The update to Vue3 required a refactoring of every (30+) components to using the composition API https://vuejs.org/api/composition-api-setup.html#basic-usage
    * Most of the vue2 related packages did/do not have equivalent vue3 packages, resulting in their replacement/removal being warranted.
      * Removed with no replacement: Password strength indicator (Custom zxcvbn component required)
      * Replaced: Bootstrap -> [balm-ui](https://material.balmjs.com/)
      * Replaced vue-multiselect with balm-ui selector component

Security changes
  * sha512 hashing password that's stored in memory after login
    * Edge case: Restoring from old beet backup would be encrypted with raw password instead of the hash, so legacy checkbox was included for anyone who might have restored an old wallet instead of creating a new wallet.
  * Removed cert stored in repo, fetches cert from beet cert repo
    * Automated tools search for these certs & report to the issuer
    * We should consider encrypting/encoding the external repo cert to further hide cert
  * Beet client doesn't respond to queries unless logged in
  * Additional store getter functions created to reduce handling of excessive data in vue components
  * Uplift of packages across the board for security vulnerability bump
  * Prompts are now much more isolated from the rest of the wallet, now launch their own electron BrowserWindow where user input data is passed as url encoded parameters. These prompts are isolated and can't access the main beet window state.
  * elliptic replaced with `secp from "@noble/secp256k1"` and @noble/ed25519 for key exchange

UI changes
  * Language selector component hidden from dashboard since there's only one language
  * Main electron window bar isn't skinned
    * pro: easier to move the window, uses system app frame
    * con: no longer goes to task tray when closed
    * Could be re-implemented
  * Balm-UI used instead of Bootstrap, deviating from the brand guide
  * Debug console can be accessed via 'alt' then view -> debug tools.
  * Sending BEET to system tray is also in the view menu.
  * Balance in dashboard and linked apps list in settings are now scroll-able lists

New functionality
  * Sign NFT_Object for NFT creation
  * Broadcast & Update assets - for NFT issuance tool
  * Prompts are now isolated popup windows instead of alert boxes within the main window

Maintenance based decisions
  * After updating packages the icons broke, so the skinned window frame was replaced with system window frame.
  * Elliptic package was replaced as it hadn't been updated in more than 2 years
  * The custom BeetWS WebSocket implementation was replaced with socket.io
    * This prove to require a large refactoring of the beetserver, blockchainfactory and beet-js library.
    * It's far more maintained & supports multiple environments

### CODE REVIEW

**Comment by grctest** [comment]
The primary purpose of this pull request was to uplift the wallet to an evergreen state, avoiding old unmaintained libraries and running the latest versions of everything to maintain a safe wallet for the Bitshares community to use.

Due to the significance of the migration from VUE2 to VUE3 a lot more work was required than initially expected, however it's now in a 99% complete state with [changes to beet-js](https://github.com/bitshares/beet-js/pull/44) needing to be merged prior to properly configuring this PR's package.json to properly build from beet-js (instead of manually placing the folder in the node_modules folder).

Changelog summary:
* Attempted to update all package dependencies
* Successfully migrated from vue2 to vue3
* Swapped bootstrap for balm-ui (vue3 wasn't supported)
* Temporarily removed support for several of the cryptos due to their libraries being outdated (can be added back in later once uplifted, though may require you maintain/fork those libraries for use).
* Had to use querystrings to pass data to popup prompts, due to ipcmain/render changes
* Prompts are no longer growl notifications, but are instead seperate popup prompt windows which only appear if the wallet is fully unlocked and key exchanged with the client.
  * Added security benefit of prompts not having any access to store data & prompts only show once all required data is fetched.
* Using socket.io for websocket connections to client, instead of maintaining a complex websocket implementation in beet.
* Checks for wallet being unlocked when receiving requests, rejecting if locked.
* Additional documentation of functions throughout codebase
* Changing window ui so it's not custom borderless, now the system menubar can be accessed via alt for debug.
* Popup prompts trigger both a prompt window as well as a system notification. Encountered errors inc wrong passwords are logged to system notifications.
* Verify status of blockchain nodes, attempt to connect to fastest, avoid using dead urls.
* Fixed the backup functionality, now it properly exports and restores a backup.
* Memory key security improvements (needs regression testing when using a legacy account in the new wallet, perhaps specifically backing up again doesn't fully decrypt the old keys before the new backup is encrypted, so it doesn't fully decrypt after restoring and unlocking the new backup of the old account).
* Attempts to implement i18n locale switching, halted due to prioritization of beet wallet being refocused to the prompt functionality.
* Avoid use of v-html to avoid potential XSS

Looking forwards to any change requests reviewers have, I appreciate the work it'll take to review this, in the future PR's will be far smaller, it's just that this was a huge change due to electron/vue/websocket changes.

**Comment by grctest** [comment]
Now all prompts aside from known issue https://github.com/bitshares/beet-js/pull/44#issuecomment-1134945645 are fully operational.

Known issues:
* Open app -> add account -> back => erroneous state requires refresh
* If an error is thrown you must unlink/link to get a new keypair. Exchanging keys or keeping the old keys on error is the fix.
* Refreshing the view creates an erroneous state which requires logging out then back into the wallet.

Looking forwards to the review, my current efforts are complete.

**Comment by sschiessl-bcp** [comment]
What is the current policy on Mac/Safari with connections without ssh? We added https back then also because otherwise it's blocked on Mac

**Comment by sschiessl-bcp** [comment]
image

Am I doing something wrong or is this the current front?

**Comment by grctest** [comment]
That's the current front, yeah. The styling of the dropdown and password input could be better however that might be outwith the MVP as it currently works.

I've not got a Mac device so I've been unable to test it cross platform. It works in firefox and chrome at least, which meets MVP criteria.

Since hardcoding certs in the repo isn't appropriate, I'd probably recommend [mkcert](https://www.npmjs.com/package/mkcert) or [@small-tech/https](https://www.npmjs.com/package/@small-tech/https) to generate and install a local cert to reintroduce Mac safari support, however this was deemed out of scope for this PR in telegram.

**Comment by sschiessl-bcp** [comment]
Balances not being loaded when opening legacy account
image

**Comment by grctest** [comment]
I've committed a fix for the balance component, it should automatically display the balance now instead of requiring a button press after the first attempt.

I agree that we should remove the node selection in user setup, the blockchain api now automatically picks the fastest node for the client, so I'll sort that out.

Indeed I need to figure out how to send the user back to the login page, this erroneous state also occurs if you force refresh the dashboard when logged in.

**Comment by grctest** [comment]
How about now? I've removed the node selection drop down & fixed the back button state glitch

**Comment by grctest** [comment]
> In general, I think a user should not have to select nodes for a chain when creating an account. This may be a general setting, or better, beet finds a working node itself

The user no longer manually selects the node, the client will asc sort the nodes by lag, then try the fastest and auto fail-over to the next node. This might result in the first click or two registering not working till a working node responds.

**Comment by sschiessl-bcp** [comment]
- please make the spacings usable for now. we need to follow up with another PR to get back to former coherent UX (https://github.com/bitshares/beet/issues/34#issuecomment-441528538)
- transfer example works, yay! Good job! Relinking does not work, you mentioned that is known issue
- sign message gives a malformed utf8 exception

**Comment by sschiessl-bcp** [comment]
It is now displaying properly on my Laptop, nothing cut out anymore! 

Signing a message is now also working properly. What is the purpose of the Signature Verification dialog?

**Comment by grctest** [comment]
The sign message example script immediately attempts to verify the signed message, by verifying the signed message it proves that the signed message was valid. The prompt requests permission to perform the verification, perhaps the info could be conveyed better in the prompt?

I could have made it a separate script, but then would have needed to save the output of the signMessage script for input in the verifyMessage script.

After looking more into the mkcert option for https, I've decided to reintroduce part of the old https method, to improve compatibility. Will update the beet-js to detect if https or http is up & commit once working.

**Comment by sschiessl-bcp** [comment]
> The sign message example script immediately attempts to verify the signed message, by verifying the signed message it proves that the signed message was valid. The prompt requests permission to perform the verification, perhaps the info could be conveyed better in the prompt?
> 
> I could have made it a separate script, but then would have needed to save the output of the signMessage script for input in the verifyMessage script.
> 
> After looking more into the mkcert option for https, I've decided to reintroduce part of the old https method, to improve compatibility. Will update the beet-js to detect if https or http is up & commit once working.

That's an unnecessary double check for the user. No single one will actually validate that signature by hand since you just created it. You can of course validate the signature directly after creating it, but asking the user to OK that is breaking UX. User must trust Beet to sign properly.

**Comment by grctest** [comment]
Alright, I'll make the message verification automatic without user prompt.

**Comment by grctest** [comment]
Message verification prompt is gone now.
Reintroduced https alongside http, fetches certs from beet cert repo.
Added an nft_object signing api function prompt for streamlining NFT issuance on BTS.
Also fixed an issue with the signmessage function, it was signing null instead of messageText.

I feel like this is ready for merge at this point :)

**Comment by sschiessl-bcp** [comment]
There are some UX issues and other minor issues to be worked out, but general flow works.

**Comment by sschiessl-bcp** [comment]
@clockworkgr 

Beetlejuice Beetlejuice Beetlejuice

Interested in skimming this PR a bit?

**Comment by grctest** [comment]
Summary of changes in PR:
* npm-check-updates was initially used to identify packages which could be updated
  * About half of the packages were able to be updated with minor changes
  * Some of the updated packages introduced severe breaking changes, namely vue2 -> vue3
    * The update to Vue3 required a refactoring of every component to using the composition API https://vuejs.org/api/composition-api-setup.html#basic-usage
    * Most of the vue2 related packages did/do not have equivalent vue3 packages, resulting in their replacement/removal being warranted.
      * Removed with no replacement: Password strength indicator (Custom zxcvbn component required)
      * Replaced: Bootstrap -> [balm-ui](https://material.balmjs.com/)
      * Replaced vue-multiselect with balm-ui selector component
* Security changes
  * sha512 hashing password that's stored in memory after login
  * Removed cert stored in repo, fetches cert from another repo
    * Automated tools search for these certs & report to the issuer
    * We should consider encrypting/encoding the external repo cert to further hide cert
  * Beet client doesn't respond to queries unless logged in
  * Additional store getter functions created to reduce handling of excessive data in vue components
  * Uplift of packages across the board for security vulnerability bump
  * Prompts are now much more isolated from the rest of the wallet, now launch their own electron BrowserWindow where user input data is passed as url encoded parameters. These prompts are isolated and can't access the main beet window state.
  * elliptic hasn't been updated in 2 years, replaced with `secp from "@noble/secp256k1"` and @noble/ed25519 for key exchange

* UI change
  * Language selector component removed since there's only one language
  * Main electron window bar isn't skinned
    * pro: easier to move the window, uses system app frame
    * con: no longer goes to task tray when closed
    * Could be re-implemented
  * Balm-UI used instead of Bootstrap, deviating from the brand guide
  * Debug console can be accessed via 'alt' then view -> debug tools.
  * Sending BEET to system tray is also in the view menu.

* New functionality
  * Sign NFT_Object for NFT creation
  * Broadcast & Update assets - for NFT issuance tool
  * Prompts are now isolated popup windows instead of alert boxes within the main window

* Maintenance based decisions
  * The custom BeetWS WebSocket implementation was replaced with socket.io
    * This prove to require a large refactoring of the beetserver, blockchainfactory and beet-js library.
    * It's far more maintained & supports multiple environments

**Comment by abitmore** [comment]
> Summary of changes in PR:

Thanks. Copied to OP.

**Review by abitmore — COMMENTED** [review]
> Removed cert stored in repo, fetches cert from beet cert repo

Where is the "beet cert repo"?

**Comment by grctest** [comment]
https://github.com/beetapp/beet-certs

**Comment by abitmore** [comment]
> https://github.com/beetapp/beet-certs

Thanks.

Looks like the certs aren't getting updated automatically. If it's a Let's encrypt cert, since it points to `127.0.0.1`, I don't think it can be updated by running `certbot` via Github Actions.

By the way, we'd better use a repo in the bitshares organization.

**Comment by grctest** [comment]
Want to create such a bts cert repo? Or shall such a change be introduced in a future pull request?

**Comment by sschiessl-bcp** [comment]
This is a monster, lets do with new PR

**Pull request merged**
