### PR TITLE
Multi-account/Multi-chain 

### PR DESCRIPTION
**Pull request by clockworkgr**
Add UX flows
Add multi-chain support to popups and signing

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Signup flow and text needs to be changed to fit the new model (one wallet for all):
image

**Comment by sschiessl-bcp** [comment]
Preselect if only one present:
image

Also consider using "Select account to provide." as the placeholder (empty combo is ugly)

**Comment by sschiessl-bcp** [comment]
When adding a second account I had to enter a password in the wizard

**Comment by sschiessl-bcp** [comment]
After connecting and reloading the page, the locally stored identity does not contain a chain

```
account_id: "1.2.886902"
appName: "My App"
apphash: "c4836b1ac044fafe988d4321cb0f1d201339ea2bde9b3b7fcd3fc123d2693e9e"
chain: undefined
id: 1
...
```

**Comment by clockworkgr** [comment]
> When adding a second account I had to enter a password in the wizard

yes...wallets are stored encrypted....need the pass to reencrypt new accountlist

**Comment by clockworkgr** [comment]
> After connecting and reloading the page, the locally stored identity does not contain a chain
> 
> ```
> account_id: "1.2.886902"
> appName: "My App"
> apphash: "c4836b1ac044fafe988d4321cb0f1d201339ea2bde9b3b7fcd3fc123d2693e9e"
> chain: undefined
> id: 1
> ...
> ```

That's with the latest beet-js right? It should be injected back into the response...I'll check

**Comment by sschiessl-bcp** [comment]
Probably related to chain not set, same with identity hash. 

When trying to link multiple chains:
image

**Comment by clockworkgr** [comment]
> Probably related to chain not set, same with identity hash.
> 
> When trying to link multiple chains:
> image

fixed...apphash was accidentally left as unique in IDB

**Comment by clockworkgr** [comment]
> > After connecting and reloading the page, the locally stored identity does not contain a chain
> > ```
> > account_id: "1.2.886902"
> > appName: "My App"
> > apphash: "c4836b1ac044fafe988d4321cb0f1d201339ea2bde9b3b7fcd3fc123d2693e9e"
> > chain: undefined
> > id: 1
> > ...
> > ```
> 
> That's with the latest beet-js right? It should be injected back into the response...I'll check

fixed

**Comment by clockworkgr** [comment]
> Preselect if only one present:
> image
> 
> Also consider using "Select account to provide." as the placeholder (empty combo is ugly)

fixed

**Comment by clockworkgr** [comment]
> Signup flow and text needs to be changed to fit the new model (one wallet for all):
> image

changed copy for now...dont feel like making it 5 steps.

**Comment by sschiessl-bcp** [comment]
image

When using bitshares signed message example, first link and approve signature, then reload, see error above

**Comment by sschiessl-bcp** [comment]
> image
> 
> When using bitshares signed message example, first link and approve signature, then reload, see error above

Resolved

**Comment by sschiessl-bcp** [comment]
When adding a second account and failing to enter correct wallet password at the end, it just hangs

**Comment by sschiessl-bcp** [comment]
```
beet-js.js:41 Uncaught (in promise) Error: ConstraintError: Unable to add key to index 'identityhash': at least one key does not satisfy the uniqueness requirements.
    at l.getChainConnection (beet-js.js:41)
```

Happens with trollbox when two accounts are present after reloading with the same account. Needs more investigation

**Comment by clockworkgr** [comment]
> When adding a second account and failing to enter correct wallet password at the end, it just hangs

somehow missed this. Fixed in https://github.com/bitshares/beet/pull/70/commits/e328cb89070e00b890b13715747383d0bb81a44d

**Comment by sschiessl-bcp** [comment]
Relinking on same hash does not work 
image

Use example https://github.com/bitshares/beet-js/blob/MultipleAccounts/examples/example_multiple.html, link and reload to reproduce

**Comment by sschiessl-bcp** [comment]
Closes #71

**Pull request merged**
